on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image name'
        required: true
        type: choice
        options:
          - macos-11
          - macos-12
          - ubuntu-20
          - ubuntu-22
          - windows-2019
          - windows-2022
      version:
        description: 'Version to display'
        required: true
        type: string
      complete:
        description: 'Deployment is completed'
        required: true
        type: boolean

jobs:
  build:
    name: Update deployment status
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        env:
          GH_TOKEN: ${{ secrets.GH_GIST_TOKEN }}
        run: |
          # Set color
          if [ "${{ inputs.complete }}" == "true" ]; then
            color=green
          else
            color=orange
          fi

          # Set label
          case "${{ inputs.image }}" in
            macos-*)
              label='' ;;
            ubuntu-20)
              label='Ubuntu 20.04' ;;
            ubuntu-22)
              label='Ubuntu 22.04' ;;
            windows-*)
              label='${{ inputs.version }}' ;;
          esac
          
          # Set message
          case "${{ inputs.image }}" in
            macos-*)
              if [ "${{ inputs.complete }}" == "true" ]; then
                message='✔ ${{ inputs.version }}'
              else
                message='⭮ ${{ inputs.version }}'
              fi ;;
            ubuntu-*)
              message='${{ inputs.version }}' ;;
            windows-*)
              if [ "${{ inputs.complete }}" == "true" ]; then
                message='Updating...'
              else
                message='Updated'
              fi ;;
          esac

          filename="${{ inputs.image }}.json"
          echo "{\"schemaVersion\": 1,
            \"label\": \"$label\",
            \"message\": \"$message\",
            \"color\": \"$color\"
          }" > "${filename}"
          gh gist edit "0e7b4bad13ceb1da55245092847008e1" -a "${filename}"
